### ISSUE TITLE
Bio::DB::RefSeq install fails after exception message

### ISSUE THREAD

**Issue by shelbyLanda** [bioperl/Bio-DB-RefSeq#5]
Hello-- I am running into an issue installing RefSeq as part of bioperl installation. Below is a screen-caputure of the build log.
![Screen Shot 2020-01-24 at 1 47 17 PM](https://user-images.githubusercontent.com/17224758/73099086-56d22400-3eb0-11ea-9dc2-b160da990dc0.png)

Is there a dependency that is not obvious to me that is preventing the installation from moving forward?

**Comment by shelbyLanda** [comment]
Okay, that is the impression I was getting. Will this issue be marked resolved when its patched?

**Comment by bosborne** [comment]
EBI says this is fixed, and that test URL works now - are you still seeing that installation error?

**Comment by shelbyLanda** [comment]
Great! I ran it and the remaining modules installed without a hitch. Thanks!
